module.exports = {
  event: {
    BUTTON_CLICKED: 'BUTTON_CLICKED',
    //
    GAME_CONNECTED: 'GAME_CONNECTED',
    GAME_DISCONNECTED: 'GAME_DISCONNECTED',
    RELAY_CONNECTED: 'RELAY_CONNECTED',
    RELAY_DISCONNECTED: 'RELAY_DISCONNECTED',
    ROOM_CHANGED: 'ROOM_CHANGED'
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    USER_JOINED: 'USER_JOINED',
    UESR_LEFT: 'USER_LEFT',
    READY_CHANGED: 'READY_CHANGED'
  },
  state: {
    HOME: 'HOME',
    WAITING: 'WAITING',
    READY: 'READY',
    GAMING: 'GAMING',
    EXIT_DIALOG: 'EXIT_DIALOG'
  },
  room: {
    HOME: 'HOME',
    WAITING: 'WAITING',
    GAMING: 'GAMING'
  }
};
