module.exports = {
  event: {
    STATE_CHANGED: 'STATE_CHANGED',
    BUTTON_CLICKED: 'BUTTON_CLICKED',
    ROOM_JOINED: 'ROOM_JOINED',
    ROOM_LEFT: 'ROOM_LEFT',
    USER_DISCONNECTED: 'USER_DISCONNECTED'
  },
  state: {
    HOME: 'HOME',
    WAITING: 'WAITING',
    READY: 'READY',
    GAMING: 'GAMING',
    EXIT_DIALOG: 'EXIT_DIALOG'
  },
  room: {
    HOME: 'HOME',
    WAITING: 'WAITING',
    GAMING: 'GAMING'
  }
};
