const STATE_CHANGED = 'STATE_CHANGED';
const EXIT_DIALOG = 'EXIT_DIALOG';
const BUTTON_CLICKED = 'BUTTON_CLICKED';
const ROOM_JOINED = 'ROOM_JOINED';
const ROOM_LEFT = 'ROOM_LEFT';

module.exports = {
  STATE_CHANGED,
  EXIT_DIALOG,
  BUTTON_CLICKED,
  ROOM_JOINED,
  ROOM_LEFT
};
